# Generated by Django 6.0.4 on 2026-04-11 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id_actor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'actores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id_director', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'directores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'generos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id_pelicula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('anio', models.IntegerField(db_column='anio')),
                ('resumen', models.TextField(blank=True, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'peliculas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id_plataforma', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'plataformas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeliculaActor',
            fields=[
                ('pelicula', models.ForeignKey(db_column='id_pelicula', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='movies.pelicula')),
            ],
            options={
                'db_table': 'pelicula_actor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeliculaPlataforma',
            fields=[
                ('pelicula', models.ForeignKey(db_column='id_pelicula', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='movies.pelicula')),
            ],
            options={
                'db_table': 'pelicula_plataforma',
                'managed': False,
            },
        ),
    ]
